### ISSUE TITLE
Can't fetch the exchange rates from BTC to any currency

### ISSUE THREAD

**Issue by vivekrj0** [elixir-europe/TEStribute#70]
**Describe the bug**
When the target_currency sets to 'BTC' in [fetch_exchange_rates('BTC', ['USD'])](https://github.com/elixir-cloud-aai/TEStribute/blob/c44174bbde60ee27e52e2fa2eb67d122a440c724/TEStribute/utils/service_calls.py#L404) it shows KeyError.
As the key which  is accessed and isn't found in the rates_select['BTC'].

**Expected behavior**
` File "service_calls.py", line 512, in fetch_exchange_rates
    rate_btc = rates_select['BTC']
KeyError: 'BTC'
`

**Desktop**

- OS: [Ubuntu]
- Browser [Firefox]
- Version [18.04 LTS]

**Comment by vivekrj0** [comment]
I am working on it.

**Comment by uniqueg** [comment]
Closed by #71
